Land new code in master for final testing (#870)
* Bulk replace all files from heavydb-internal
* Rename all heavydb-internal/heavydb_internal to heavydb

CI TESTING STILL ONGOING
SOME DOCUMENTATION IS INCOMPLETE

diff --git a/scripts/innerstartheavy b/scripts/innerstartheavy
--- a/scripts/innerstartheavy
+++ b/scripts/innerstartheavy
@@ -1,4 +1,6 @@
 #!/bin/bash
+# SPDX-FileCopyrightText: Copyright (c) 2015-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
+# SPDX-License-Identifier: Apache-2.0
 
 set -e
 PID=$$
@@ -13,7 +15,6 @@ function get_script_location()    # https://stackoverflow.com/a/246128
     SOURCE="${BASH_SOURCE[0]}"
     while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
       DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
-      # Note symlinks will fail on macOS due to missing readlink command
       SOURCE="$(readlink "$SOURCE")"
       [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
     done
@@ -70,11 +71,9 @@ while (( $# )); do
             shift
             LIBGEOS_PATH="$1" ;;
         --non-interactive)
-            INSERT_SAMPLE_DATA=false ;;
+            ;;
         --disable-open-frontend)
             DISABLE_OPEN_FRONTEND=true ;;
-        --sample-data)
-            INSERT_SAMPLE_DATA=true ;;
         --verbose)
             VERBOSE="--verbose" ;;
         *)
@@ -88,7 +87,6 @@ echo "Backend TCP:  localhost:${MAPD_TCP_PORT}"
 echo "Backend HTTP: localhost:${MAPD_HTTP_PORT}"
 echo "Frontend Web: localhost:${MAPD_WEB_PORT}"
 echo "Calcite TCP:  localhost:${MAPD_CALCITE_PORT}"
-echo "HeavyIQ HTTP:  localhost:${MAPD_HEAVYIQ_PORT}"
 
 if [ ! -d $MAPD_DATA ]; then
     mkdir -p $MAPD_DATA
@@ -110,26 +108,16 @@ else
     unset LEGACY
 fi
 
-MACHINE_ARCH=$(uname -m)
-for i in "/etc/xdg" "/etc" "/usr/local/share" "/usr/share"; do
-  if [ -f "$i/vulkan/icd.d/nvidia_icd.json" ]; then
-    icd_path="$i/vulkan/icd.d/nvidia_icd.json"
-    break
-  elif [ -f $i/vulkan/icd.d/nvidia_icd.$MACHINE_ARCH.json ]; then
-    icd_path=$i/vulkan/icd.d/nvidia_icd.$MACHINE_ARCH.json
-    break
-  fi
-done
+# shellcheck source=nvidia-graphics-env.sh
+source "$DIR/scripts/nvidia-graphics-env.sh"
 
-if [[ -z "$icd_path" ]]; then
+if ! export_nvidia_graphics_env; then
   YELLOW='\033[1;33m'
   NORMAL='\033[0m'
   LBLUE='\033[1;34m'
   echo -e "${YELLOW}Warning: ${NORMAL}Cannot find the Nvidia Vulkan driver manifest file \"nvidia_icd.json\" in the expected system directories. As a result the backend renderer may not work.
   Please verify that the nvidia driver and vulkan loader are installed appropriately.
   See: ${LBLUE}https://docs.omnisci.com/troubleshooting/vulkan-graphics-api-beta#bare-metal-installs${NORMAL} for some installation and troubleshooting tips."
-else
-    export VK_ICD_FILENAMES=$icd_path
 fi
 
 # prepend libgeos DSO path to $LD_LIBRARY_PATH if valid
@@ -151,12 +139,6 @@ fi
 ./bin/heavydb $MAPD_DATA $RO --port $MAPD_TCP_PORT --http-port $MAPD_HTTP_PORT --calcite-port $MAPD_CALCITE_PORT $CONFIG $VERBOSE ${FORWARDED_ARGS[@]} &
 PID1=$!
 echo "- heavydb $PID1 started"
-
-if [ "$INSERT_SAMPLE_DATA" = true ]; then
-    echo "- waiting 5s before inserting sample data"
-    sleep 5
-    . "$DIR/insert_sample_data"
-fi
 
 if [ -d frontend ] && [ -e ./bin/heavy_web_server ]; then
     # use https for backend-url if both ssl-cert and ssl-key options are in the config file
@@ -191,6 +173,16 @@ if [ -d frontend ] && [ -e ./bin/heavy_web_server ]; then
     else
         echo "Navigate to: $MAPDFRONTEND"
     fi
+fi
+
+if [[ -d heavyiq ]]; then
+    # Execute the HeavyIQ startup script in a subshell in order to avoid
+    # possible conflicts from virtual environment activation.
+
+    # Always start HeavyIQ, it will do it's own checks and bail if failed
+    # Specifically if it's _not_ free edition and there's no config
+    # -or- if a `disabled`` config flag is specified in `[iq]` it will bail
+  ($DIR/scripts/start_heavyiq.sh)
 fi
 
 if [ "$LEGACY" = "" ]; then
